version: 2
jobs:
  build:
    environment:
      USER_NAME: a5-receptionist
      USER_EMAIL: receptionist@altus5.com
      STAGING_USER_NAME: char-siu-men
      STAGING_USER_EMAIL: char.siu.men@gmail.com
    working_directory: ~/wsk
    docker:
      - image: altus5/web-starter-kit:0.6.5_1
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            pwd
            ls
            if [ "${CIRCLE_BRANCH}" == "draft" ]; then
              echo ${CIRCLE_BRANCH}
            fi
